### ISSUE TITLE
"Call" method ineffective in TelephonyController.

### ISSUE THREAD

**Issue by zerobandwidth** [zerobandwidth-net/android#17]
Defect observed in testing with an application that consumes `TelephonyController`.

It appears that the `call( String, String )` method promised by the AIDL prototype is not valid, and a new method must be discovered.

```
net.zerobandwidth.android.lib.telephony.exceptions.ControllerInvocationException: Failed to invoke method [call] of telephony controller.
    at net.zerobandwidth.android.lib.telephony.TelephonyController.invoke(TelephonyController.java:291)
    at net.zerobandwidth.android.lib.telephony.TelephonyController.call(TelephonyController.java:319)
Caused by: java.lang.NoSuchMethodException: call []
    at java.lang.Class.getMethod(Class.java:671)
    at net.zerobandwidth.android.lib.telephony.TelephonyController.invoke(TelephonyController.java:287)
    at net.zerobandwidth.android.lib.telephony.TelephonyController.call(TelephonyController.java:319) 
```

**Comment by zerobandwidth** [comment]
Using reflection on the interface, the following API was discovered:
```
D/TelephonyController: *** DEBUG *** Methods discovered in ITelephony:
public abstract boolean com.android.internal.telephony.ITelephony.IsDomesticRoaming() throws android.os.RemoteException
public abstract boolean com.android.internal.telephony.ITelephony.IsInternationalRoaming() throws android.os.RemoteException
public abstract [B com.android.internal.telephony.ITelephony.NSRI_requestProc(int,byte[]) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.SimSlotActivation(boolean) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.SimSlotOnOff(int) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.answerRingingCall() throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.answerRingingCallForSubscriber(int) throws android.os.RemoteException
public abstract android.os.IBinder android.os.IInterface.asBinder()
public abstract java.lang.String com.android.internal.telephony.ITelephony.calculateAkaResponse(byte[],byte[]) throws android.os.RemoteException
public abstract android.os.Bundle com.android.internal.telephony.ITelephony.calculateGbaBootstrappingResponse(byte[],byte[]) throws android.os.RemoteException
public abstract [B com.android.internal.telephony.ITelephony.calculateNafExternalKey(byte[]) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.call(java.lang.String,java.lang.String) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.callForSubscriber(int,java.lang.String,java.lang.String) throws android.os.RemoteException
public abstract int com.android.internal.telephony.ITelephony.checkCarrierPrivilegesForPackage(java.lang.String) throws android.os.RemoteException
public abstract int com.android.internal.telephony.ITelephony.checkNSRIUSIMstate_int() throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.dial(java.lang.String) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.dialForSubscriber(int,java.lang.String) throws android.os.RemoteException
public abstract boolean com.android.internal.telephony.ITelephony.disableDataConnectivity() throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.disableLocationUpdates() throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.disableLocationUpdatesForSubscriber(int) throws android.os.RemoteException
public abstract boolean com.android.internal.telephony.ITelephony.enableDataConnectivity() throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.enableLocationUpdates() throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.enableLocationUpdatesForSubscriber(int) throws android.os.RemoteException
public abstract void com.android.internal.telephony.ITelephony.enableVideoCalling(boolean) throws android.os.RemoteException
public abstract boolean com.android.internal.telephony.ITelephony.endCall() throws android.os.RemoteException
public abstract boolean com.android.internal.telephony.ITelephony.endCallForSubscriber(int) throws android.os.RemoteException
public abstract boolean com.android.internal.telephony.ITelephony.getActiveFgCallState() throws android.os.RemoteException
public abstract int com.android.internal.telephony.ITelephony.getActivePhoneType() throws android.os.RemoteException
public abstract int com.android.internal.telephony.ITelephony.getActivePhoneTypeForSubscriber(int) throws android.os.RemoteException
public abstract java.util.List com.android.internal.telephony.ITelephony.getAllCellInfo() throws android.os.RemoteException
public abstract [B com.android.internal.telephony.ITelephony.getAtr() throws android.os.RemoteException
public abstract [B com.android.internal.telephony.ITelephony.getAtrUsingSlotId(int) throws android.os.
```

A method with the `void call( String, String )` prototype is clearly visible in the list. Perhaps the generic invocation method in `TelephonyController#invoke( String, Object… )` is not valid?

**Comment by zerobandwidth** [comment]
Yep, the `getMethod()` call needs the types of all the expected parameters, so the `TelephonyController#invoke(String,Object…)` approach proved to be too naïve.

The class will have to explicitly supply the expected class types when getting the method.

**Comment by zerobandwidth** [comment]
:white_check_mark: Done.

Figured out how to extend `invoke()` to handle arguments properly. I'm not honestly sure this is any better than just replicating the exception handler in every method… Oh, well.
