### ISSUE TITLE
`.database.sqlitehouse` — Exception observed while testing in customer app.

### ISSUE THREAD

**Issue by zerobandwidth** [zerobandwidth-net/android#47]
```
E/CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 8 columns.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: [REDACTED], PID: 20368
    java.lang.RuntimeException: Unable to create service [REDACTED]: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3818)
        at android.app.ActivityThread.access$2100(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
    Caused by: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetLong(Native Method)
        at android.database.CursorWindow.getLong(CursorWindow.java:524)
        at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
        at net.zerobandwidth.android.lib.database.sqlitehouse.refractor.LongLens.fromCursor(LongLens.java:44)
        at net.zerobandwidth.android.lib.database.sqlitehouse.refractor.LongLens.fromCursor(LongLens.java:14)
        at net.zerobandwidth.android.lib.database.sqlitehouse.SQLiteHouse.fromCursor(SQLiteHouse.java:1263)
        at net.zerobandwidth.android.lib.database.sqlitehouse.SQLiteHouse.fromCursor(SQLiteHouse.java:1291)
        at net.zerobandwidth.android.lib.database.sqlitehouse.SQLiteHouse.processResultSet(SQLiteHouse.java:1313)
        at [REDACTED]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3808)
        at android.app.ActivityThread.access$2100(ActivityThread.java:222) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7229) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

In the `fromCursor` method (l.1263) we should handle the `IllegalStateException` thrown when a cursor can't resolve a column. The handler should log the exception as an error but skip the attempt to marshal that column.

**Comment by zerobandwidth** [comment]
:white_check_mark: Fix confirmed in conjunction with customer app.
